export const students = [
  {
    id: 1,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '233',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 2,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 3,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 4,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 5,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 6,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 7,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 8,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 9,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 10,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 11,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 12,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 13,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 14,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 15,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 16,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 17,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 18,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 19,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 20,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 21,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 22,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 23,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 24,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 25,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 26,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 27,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
  {
    id: 28,
    name: 'Muhammad',
    surname: 'Abdulloh',
    email: 'example@gmail.com',
    img: '../../src/assets/img/muslim_prof.jpg',
    group_number: '25',
    grade: 'Freelance',
    createdAt: '2005.01.27',
    id_number: '1234'
  },
]
